In [1]:
# No matter what the data are, the first step in making them analyzable will be to transform them into arrays of numbers.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
np?

In [4]:
# Python code
result = 0
for i in range(100):
    result += i

In [5]:
print(result)

4950


In [6]:
for i in range(5):
    print (i)

0
1
2
3
4


In [7]:
x = 4
x = "four"
print(x)

four


In [8]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L[0])

int

In [10]:
L2 = [ str (c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [15]:
L3 = [True, "2" , 3.0, 4]
M = [type (c) for c in L3]
M

[bool, str, float, int]

In [16]:
import array
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# First, we can use np.array to create arrays from Python lists:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [18]:
# NumPy is constrained to arrays that all contain the same type, if not Numpy will up cast
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
# to specify the datatype of the resulting array, using dtype
np.array([1,2,3], dtype = 'float32')

array([1., 2., 3.], dtype=float32)

In [21]:
# creat multidimensional array
M = np.array([range(i, i + 3) for i in [2,4,6]])
M

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [23]:
M.shape

(3, 3)

In [18]:
# creating arrays from scratch

In [24]:
# create length-10 array of 0
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(0,4) # equivalent to np.arange(4)

array([0, 1, 2, 3])

In [23]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3)) # https://www.w3schools.com/python/numpy/numpy_random.asp

array([[0.30514324, 0.31451548, 0.02607739],
       [0.78401325, 0.62609945, 0.53132123],
       [0.11618246, 0.51733446, 0.70769124]])

In [35]:
class Person: # create a clase, here self is a reference to the current instance 
  def __init__(self, name, age): # is used to access variables that belong to the class
    self.name = name # you can call it whatever you like, but it has to be the first parameter of any function in the class
    self.age = age # Methods in objects are functions that belong to the object

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


In [34]:
np.random.rand(3,2)

array([[0.21067187, 0.49233246],
       [0.82396868, 0.93185493],
       [0.61411884, 0.18128354]])

In [38]:
import mymodule # how to create a module
mymodule.greeting('wen')

Hello, wen


In [6]:
# function copy
def welcome():
    return 'welcome to'

In [7]:
wel = welcome()

In [8]:
wel # function copy

'welcome to'

In [9]:
del welcome


In [10]:
wel

'welcome to'

In [25]:
# closure : a function in a function
def main_welcome(msg):
    
    def sub_welcome_class():
        print('Welcome to my channel')
        print(msg)
        print("Please feel at home")
    return sub_welcome_class()

In [26]:
main_welcome("Wen")

Welcome to my channel
Wen
Please feel at home


In [32]:
def main_welcome(func): # closure & initial decorators
    
    def sub_welcome_class():
        print('Welcome to my channel')
        print(func([1,2,3]))
        print("Please feel at home")
    return sub_welcome_class()

In [33]:
main_welcome(len)

Welcome to my channel
3
Please feel at home


In [34]:
# create your own function and pass it as a parameter in a function
def main_welcome(func):
    
    def sub_welcome_class():
        print('Welcome to my channel')
        func()
        print("Please feel at home")
    return sub_welcome_class()

In [35]:
def channel_name():
    print("This is fun")

In [36]:
main_welcome(channel_name)

Welcome to my channel
This is fun
Please feel at home


In [37]:
@main_welcome # you can also do this. @main_welcome this is the decorator which calls the above decorator function, the 
def channel_name(): # below function name will pass as a parameter in the decorator function
    print("This is fun") # a decorator function can be reused

Welcome to my channel
This is fun
Please feel at home


In [36]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(1,2,(3,3))

array([[ 4.61397505,  1.92648803, -2.73604086],
       [ 0.79126413,  0.50629216, -0.01072411],
       [ 3.50650206,  2.58590256,  2.28836187]])

In [26]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint (0,10, (3,3))

array([[6, 8, 6],
       [9, 9, 2],
       [3, 7, 9]])

In [27]:
# Create a 3x3 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(4)

array([1., 1., 1., 1.])

In [29]:
# NumPy Standard Data Types
np.zeros(10,dtype = 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.ones(10,dtype = np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [31]:
# standard NumPy data types 
# https://learning.oreilly.com/library/view/python-data-science/9781491912126/ch02.html

In [32]:
# NumPy Array Attributes

In [33]:
# seed for reproducibility
np.random.seed(0)
x1 = np.random.randint (10,size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [34]:
x1

array([5, 0, 3, 3, 7, 9])

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [37]:
print("x3 ndim:" , x3.ndim)
print("x3 shape:" , x3.shape)
print("x3 size:" , x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [38]:
print("x3 dtype:" , x3.dtype)

x3 dtype: int32


In [39]:
print ("x3 itemsize:" , x3.itemsize, "bytes")
print ("x3 nbytes:" , x3.nbytes, "bytes")

x3 itemsize: 4 bytes
x3 nbytes: 240 bytes


In [40]:
# array indexing 

In [41]:
x1

array([5, 0, 3, 3, 7, 9])

In [42]:
x1[0]

5

In [43]:
x1[4]

7

In [44]:
x1[-1]

9

In [45]:
x1[-2]

7

In [46]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [47]:
x2[0,0]

3

In [48]:
x2[2,0]

1

In [49]:
x2[2,-1]

7

In [50]:
# You can also modify values using any of the above index notation:

In [51]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
# if you attempt to insert a floating-point value to an integer array, the value will be silently truncated
x1[0] = 3.14
x1

array([3, 0, 3, 3, 7, 9])

In [53]:
# Array Slicing: Accessing Subarrays x[start:stop:step]

In [54]:
# one dimensioanl
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[:5]

array([0, 1, 2, 3, 4])

In [56]:
x[5:]

array([5, 6, 7, 8, 9])

In [57]:
x[4:7]

array([4, 5, 6])

In [58]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [59]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [60]:
# all elements, reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
# reversed every other from index 5
x[5::-2]

array([5, 3, 1])

In [62]:
# Multidimensional subarrays

In [63]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [64]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [65]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [66]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [67]:
# first column of x2
print(x2[:,0])

[12  7  1]


In [68]:
# first row of x2
print(x2[0,:])

[12  5  2  4]


In [69]:
x2[0]

array([12,  5,  2,  4])

In [70]:
# SUBARRAYS AS NO-COPY VIEWS

In [72]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [73]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [74]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [75]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [76]:
# CREATING COPIES OF ARRAYS
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [77]:
# If we now modify this subarray, the original array is not touched:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [78]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [79]:
# Reshaping of Arrays
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
grid1 = grid.reshape((3,3))
grid1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
x = np.array([1,2,3])
# row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [82]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [83]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [84]:
# column vector via newaxis
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [85]:
x

array([1, 2, 3])

In [86]:
# Array Concatenation and Splitting

In [87]:
# concatenation
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [88]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [89]:
# for two-dimensional arrays
grid = np.array([[1,2,3],[4,5,6]])

In [90]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [91]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [92]:
np.concatenate([grid,grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [93]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [96]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [97]:
# SPLITTING OF ARRAYS

In [98]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [99]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [101]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [102]:
# computation on NumPy

In [105]:
# vectorized operations helps quickly execute repeated operations on values in arrays
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [106]:
# ufunc on multidimensional arrays
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [107]:
# Exploring NumPy’s UFuncs

In [108]:
# ARRAY ARITHMETIC
x = np.arange(4)
print("x  =", x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x *2", x*2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x  = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x *2 [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [109]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [110]:
-(0.5 * x + 1) **2

array([-1.  , -2.25, -4.  , -6.25])

In [111]:
# the + operator is a wrapper for the add function
np.add(x , 2)

array([2, 3, 4, 5])

In [112]:
np.subtract(x , 2)

array([-2, -1,  0,  1])

In [113]:
np.negative(x)

array([ 0, -1, -2, -3])

In [114]:
np.multiply(x , 2)

array([0, 2, 4, 6])

In [115]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [116]:
np.floor_divide(x,2)

array([0, 0, 1, 1], dtype=int32)

In [117]:
np.power(x,2)

array([0, 1, 4, 9], dtype=int32)

In [118]:
np.mod(x,2)

array([0, 1, 0, 1], dtype=int32)

In [119]:
# ABSOLUTE VALUE
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [120]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [121]:
np.add(np.abs(x),1)

array([3, 2, 1, 2, 3])

In [122]:
# complex number and returns the magnitude
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [123]:
# TRIGONOMETRIC FUNCTIONS

In [124]:
import numpy as np
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [125]:
print("theta =", theta)
print("sin(theta) = " , np.sin(theta))
print("cos(theta) = " , np.cos(theta))
print("tan(theta) = " ,np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [126]:
# Inverse trigonometric functions
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [128]:
# EXPONENTS AND LOGARITHMS
x = [1,2,3]
print("x =",x)
print("e^x = ", np.exp(x))
print("2^x =" , np.exp2(x))
print("3^x =", np.power(3,x))

x = [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [129]:
#the logarithms, are also available
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [130]:
# for very small x
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [131]:
# SPECIALIZED UFUNCS
from scipy import special

In [132]:
# Gamma functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [139]:
# Advanced Ufunc Features
# specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y

array([ 0., 10., 20., 30., 40.])

In [140]:
y = np.zeros(10)
np.power(2,x, out = y[::2])
y # out means the location in which the result is stored

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [141]:
# AGGREGATES

In [142]:
x = np.arange(1,6)
np.add.reduce(x)

15

In [143]:
np.multiply.reduce(x)

120

In [144]:
# to store all the intermediate results
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [145]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [146]:
# NumPy has dedicated functions to the results
np.sum(x)

15

In [147]:
np.prod(x)

120

In [148]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [149]:
np.cumprod(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [150]:
# outer function
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [151]:
# Aggregations: Min, Max, and Everything in Between

In [152]:
# Summing 
L = np.random.random(10)
sum(L)

6.560274560999303

In [153]:
np.sum(L)

6.560274560999303

In [154]:
big_array = np.random.rand(10)
%timeit sum(big_array)
%timeit np.sum(big_array)

2.28 µs ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.01 µs ± 97.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [156]:
# Minimum and Maximum
min(big_array) , max(big_array)

(0.02021839744032572, 0.978618342232764)

In [157]:
%timeit min(big_array)
%timeit max(big_array)

1.53 µs ± 9.03 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.58 µs ± 18.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
