In [1]:
import pandas as pd
pd.__version__

'1.2.3'

In [2]:
# pandas is built on NumPy, for data munging, pd.<TAB> namespace, pd? all the built-in documentation

In [3]:
# series, dataframe and index are the 3 basic data structure
import numpy as np

In [4]:
# series one-d array of indexed data
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
# access with values, result is an array
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
# access by index with square-bracket
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
# series as generized numpy array , the index of series does not need to be integer it can be any desired type
data = pd.Series([0.25,0.5,0.75,1.0] , index = ["a" , "b" , "c" , "d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [11]:
data = pd.Series([0.25,0.5,0.75,1.0] , index = [2 , 5 , 3, 7]) # index can be noncontinuous and nonsequential
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
data[5]

0.5

In [25]:
# series as specialized dic much more efficient than a python dic
pop_dict= {'California': 38332521,
                           'Texas': 26448193,
                           'New York': 19651127,
                           'Florida': 19552860,
                           'Illinois': 12882135}
population = pd.Series(pop_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [26]:
population['California']

38332521

In [28]:
# slicing can also be used, that is not the case of dic
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [29]:
# constructing Series objects pd.Series(data, index = index) index is optional 
pd.Series([2,4,6]) # here data is a list 

0    2
1    4
2    6
dtype: int64

In [30]:
# data can be scalar , which is repeated to fill the specified index
pd.Series(5, index = [100 , 200 , 300])

100    5
200    5
300    5
dtype: int64

In [31]:
# data can be dic so the index is the key 
pd.Series({2:"a", 1:"b", 3:"c"})

2    a
1    b
3    c
dtype: object

In [32]:
pd.Series({2:"a", 1:"b", 3:"c"} , index = [3,2]) # index can ve explicitly set if a special result is preferred

3    c
2    a
dtype: object

In [33]:
# dataframe
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [34]:
# use dic to construct a signle 2 d object containing this info
states = pd.DataFrame({"Population" : population , "Area" : area})
states

Population    Area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [35]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [36]:
states.columns

Index(['Population', 'Area'], dtype='object')

In [37]:
# df as specialized dic
states.Area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: Area, dtype: int64

In [38]:
# create a dataframe
# from a single series object
pd.DataFrame(population , columns = ["Population"])

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [39]:
# from a list of dicts
data = [{"a" : i ,"b" : 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [40]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [41]:
# even if some keys are missing, pandas will fill with NaN
pd.DataFrame([{"a" : 1, "b" : 2}, {"b" : 3, "c" : 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [42]:
# from a dic of series
pd.DataFrame({'population': population,'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [43]:
# from a 2-d NumPy array 
pd.DataFrame(np.random.rand(3,2), columns=["foo" ,"bar"], index=["a","b","c"])

foo       bar
a  0.640549  0.319627
b  0.761859  0.189925
c  0.458550  0.696597

In [44]:
# from a numpy structed array
A = np.zeros(3, dtype = [("A","i8"),("B","f8")])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [45]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [46]:
# Pandas index object
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [47]:
# index as immutable array
ind[1]

3

In [48]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [49]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [50]:
# index object is immutable so ind[1] = 0 will give you an error

In [51]:
# index as ordered set 
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [52]:
# intersection
indA & indB

C:\Users\huwen\.conda\envs\bootcamp\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  


Int64Index([3, 5, 7], dtype='int64')

In [53]:
# union
indA|indB

C:\Users\huwen\.conda\envs\bootcamp\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [54]:
# symmetric difference
indA ^ indB

C:\Users\huwen\.conda\envs\bootcamp\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  


Int64Index([1, 2, 9, 11], dtype='int64')

In [55]:
# data selection in Series
# series as dic
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [56]:
data["b"]

0.5

In [57]:
"a" in data

True

In [58]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [59]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [60]:
# adding 
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [61]:
# series as one-d array

In [62]:
# slicing by explicit index
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [63]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [64]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [65]:
# fancy indexing
data[["a","e"]]

a    0.25
e    1.25
dtype: float64

In [66]:
# indexers : loc iloc and ix
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [67]:
# explict index when indexing 
data[1]

'a'

In [68]:
#implict index when slicing 
data[1:3]

3    b
5    c
dtype: object

In [69]:
# to avoid confusion using attributes 
# loc refer to explicit index
data.loc[1]

'a'

In [70]:
data.loc[1:3]

1    a
3    b
dtype: object

In [71]:
# iloc refer to implicit python-style index
data.iloc[1]

'b'

In [72]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [73]:
# data selection in DF
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                  'New York': 19651127, 'Florida': 19552860,
                  'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [74]:
# access via dictionary style indexing of the column name:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [75]:
# attribute-style access with column names that are strings
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [76]:
data.area is data["area"]

True

In [77]:
data.pop is data["pop"] # because pop is a method in DF so it will consider more to this method than the pop columns

False

In [78]:
# add a new column
data["density"] = data["pop"]/data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [81]:
# df as 2-d array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [82]:
# we can transpose
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [83]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [84]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [85]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [87]:
data.loc[:'New York',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [90]:
# combine masking, fancy indexing and loc
data.loc[data.density > 100, ["pop","density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [91]:
# any of those indexing conventions can be used to set or modify values
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [92]:
# additional indexing conventions
# indexing refers to columns, slicing refers to rows
data["Florida":"Illinois"]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [96]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746