In [1]:
l = [1,2,3]

In [2]:
print(l)

[1, 2, 3]


In [3]:
l

[1, 2, 3]

In [4]:
len(l)

3

In [5]:
l[0]

1

In [6]:
l[len(l)-1]

3

# Title
## Subtitle
**bold**
### Markdown guide link

In [7]:
import random

In [8]:
large_list = list(range(100))

In [9]:
len(large_list)

100

In [10]:
large_list[-1]

99

In [11]:
%%timeit
sum_value = 0
for i in large_list:
    sum_value = sum_value + i

3.25 µs ± 31.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
import numpy as np

In [13]:
large_array = np.array(large_list)
large_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
type(large_array)

numpy.ndarray

In [15]:
%%timeit
large_array.sum()

1.7 µs ± 25.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## creating a numpy array

In [16]:
my_array = np.array([1,2,3,4])

In [17]:
type(my_array)

numpy.ndarray

In [18]:
len(my_array)

4

In [20]:
my_array

array([1, 2, 3, 4])

In [19]:
my_array.shape

(4,)

In [22]:
## in a numpy array, all elements are of the same data type 

In [21]:
my_3d_array = np.array([
    [[1,3],[2,4],[3,0],[4,1]],
    [[5,1],[6,3],[7,6],[8,0]],
])

In [22]:
my_3d_array.shape

(2, 4, 2)

In [25]:
## operation with NumPy

In [23]:
array1 = np.array([1,2,3,4])

In [24]:
array2 = np.array([34,9,23,4])

In [25]:
array1 + array2

array([35, 11, 26,  8])

In [26]:
array1 - array2

array([-33,  -7, -20,   0])

In [27]:
array1 * array2

array([34, 18, 69, 16])

In [28]:
np.matmul(array1,array2) # matrix product

137

In [34]:
# sum, mean max, min of an array

In [29]:
array1.sum()

10

In [30]:
array1.mean()

2.5

In [31]:
array1.max()

4

In [32]:
array1.min()

1

In [33]:
array1.argmax() # index of the max value

3

In [34]:
array2.argmax()

0

In [35]:
my_3d_array.max()

8

In [36]:
my_3d_array.max(axis=0) # the column containing the max value

array([[5, 3],
       [6, 4],
       [7, 6],
       [8, 1]])

In [37]:
my_3d_array.max(axis=1) # the row conatining the max value

array([[4, 4],
       [8, 6]])

In [45]:
my_3d_array.shape # 2 row 4 column 2 deep which means the deepth of each element

(2, 4, 2)

In [46]:
# numpy array indexing 

In [46]:
my_md_array = np.array([[1,2,3,4],[5,6,7,8]])

In [50]:
my_md_array[1]

array([5, 6, 7, 8])

In [49]:
my_md_array[1,2]

7

In [52]:
my_md_array[:,2]

array([3, 7])

In [53]:
my_md_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
my_md_array[0,:]

array([1, 2, 3, 4])

In [55]:
# boolean indexing

In [56]:
my_md_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
my_md_array <=7

array([[ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [58]:
my_md_array[my_md_array <=7]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
my_md_array[my_md_array >= 4]

array([4, 5, 6, 7, 8])

In [60]:
# power
array1 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [61]:
array1

array([1, 2, 3, 4])

In [62]:
# useful tips to create quickly numpy arrays
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
# https://www.rapidtables.com/web/color/RGB_Color.html RGB color code

In [66]:
np.ones_like((6,5,3), dtype = int)

array([1, 1, 1])

In [72]:
?np.ones_like

In [67]:
np.eye(10,dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [68]:
who

array1	 array2	 l	 large_array	 large_list	 my_3d_array	 my_array	 my_md_array	 np	 
random	 


In [70]:
array1

array([1, 2, 3, 4])

In [71]:
np.matrix(array1)

matrix([[1, 2, 3, 4]])

In [73]:
np.matrix.transpose(array1)

array([1, 2, 3, 4])

In [74]:
# broadcast

In [75]:
my_md_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
my_md_array + np.ones_like(my_md_array)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [77]:
my_md_array + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [79]:
my_md_array + np.ones_like(my_md_array) * 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [80]:
my_md_array + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [82]:
my_md_array + np.array([[1],[2]])

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [83]:
my_md_array * np.array([[1],[2]])

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16]])

In [84]:
np.array([[1],[2]]).shape

(2, 1)

In [78]:
my_md_array + np.array([[1,2,4,0]])

array([[ 2,  4,  7,  4],
       [ 6,  8, 11,  8]])

In [79]:
my_md_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])